import org.gradle.api.tasks.testing.Test

plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.robin'
version = '0.0.1-SNAPSHOT'

allprojects {
	repositories {
		mavenCentral()
	}
}

subprojects {
	apply plugin: 'java-library'
	apply plugin: 'io.spring.dependency-management'

	group = rootProject.group
	version = rootProject.version

	dependencyManagement {
		imports {
			mavenBom "org.springframework.boot:spring-boot-dependencies:4.1.0"
		}
	}

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(25)
		}
	}

	dependencies {
		compileOnly 'org.projectlombok:lombok:1.18.34'
		annotationProcessor 'org.projectlombok:lombok:1.18.34'

		//Mapstruct
		implementation 'org.mapstruct:mapstruct:1.6.3'
		annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

		//Binding Lombok - Mapstruct
		implementation 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

		testCompileOnly 'org.projectlombok:lombok:1.18.34'
		testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'
	}

	tasks.withType(Test).configureEach {
		useJUnitPlatform()
	}
}

tasks.named('build') {
	dependsOn subprojects.collect { it.tasks.named('build') }
}
