// Módulo de dominio: entidades, value objects y reglas de negocio.
dependencies {
    //Dependencias de otros módulos
    implementation project(':erp-common')
    implementation project(':erp-application')
    implementation project(':erp-infrastructure')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
}
